// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexicoCup.flex

package com.mycompany.analizadorlexico;
import java_cup.runtime.*;
import java.util.*;

import com.mycompany.analizadorlexico.TablaSimbolos;



@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner, java.io.Serializable {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\1\5\1\6\2\0\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\11\21\2\0"+
    "\1\22\1\23\1\24\2\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\2\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\36\1\44\1\45\1\46\1\47"+
    "\1\50\1\36\1\51\2\36\1\52\1\53\1\54\3\0"+
    "\1\55\3\26\1\56\1\26\1\57\1\60\3\36\1\61"+
    "\2\36\1\62\3\36\1\63\1\36\1\64\1\36\1\65"+
    "\3\36\1\0\1\66\10\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\3\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\1\1\12\2\13\1\14\1\15"+
    "\1\16\13\17\1\20\1\21\1\17\1\1\1\22\1\0"+
    "\1\23\2\0\1\24\1\25\1\0\1\2\1\0\1\26"+
    "\1\27\1\30\5\17\1\31\7\17\1\32\2\0\1\33"+
    "\4\17\1\34\1\35\6\17\2\0\1\2\1\17\1\36"+
    "\7\17\1\37\1\17\1\40\1\0\2\17\1\41\1\17"+
    "\1\42\3\17\1\43\1\0\1\44\3\17\1\45\1\46"+
    "\1\0\3\17\1\47\2\17\1\0\1\50\1\17\1\0"+
    "\1\17\12\0\1\51\2\0\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\u0181\0\u01b8\0\u01ef"+
    "\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7"+
    "\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\67"+
    "\0\67\0\u055f\0\u0596\0\67\0\334\0\67\0\u05cd\0\u0604"+
    "\0\67\0\u0181\0\u063b\0\u0672\0\u06a9\0\67\0\67\0\67"+
    "\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u0302\0\u07f3\0\u082a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\67\0\u0974\0\u09ab"+
    "\0\u06a9\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0302\0\u0302\0\u0abe"+
    "\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\67"+
    "\0\u0c76\0\u0302\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0"+
    "\0\u0df7\0\u0302\0\u0e2e\0\u0302\0\u0e65\0\u0e9c\0\u0ed3\0\u0302"+
    "\0\u0f0a\0\u0302\0\u0f41\0\u0f78\0\u0faf\0\u0302\0\u0fe6\0\u0302"+
    "\0\u101d\0\u1054\0\u108b\0\u0302\0\u0302\0\u10c2\0\u10f9\0\u1130"+
    "\0\u1167\0\67\0\u119e\0\u11d5\0\u120c\0\u0302\0\u1243\0\u127a"+
    "\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432"+
    "\0\u1469\0\u14a0\0\u14d7\0\67\0\u150e\0\u1545\0\67";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\3\25\1\26\1\27\1\30"+
    "\1\25\1\31\1\32\5\25\1\33\1\34\1\35\1\36"+
    "\1\37\2\25\1\40\1\2\1\41\6\25\1\42\2\25"+
    "\1\43\70\0\2\3\107\0\1\44\43\0\5\45\1\46"+
    "\45\45\1\47\13\45\35\0\1\50\40\0\1\51\77\0"+
    "\2\52\57\0\1\53\4\0\1\54\65\0\1\52\1\0"+
    "\2\21\12\0\1\55\23\0\1\55\24\0\1\52\1\0"+
    "\2\21\70\0\1\56\66\0\1\57\66\0\1\60\63\0"+
    "\2\25\3\0\25\25\3\0\11\25\21\0\2\25\3\0"+
    "\4\25\1\61\20\25\3\0\11\25\21\0\2\25\3\0"+
    "\12\25\1\62\1\25\1\63\10\25\3\0\11\25\21\0"+
    "\2\25\3\0\12\25\1\64\12\25\3\0\11\25\21\0"+
    "\2\25\3\0\4\25\1\65\20\25\3\0\11\25\21\0"+
    "\2\25\3\0\5\25\1\66\6\25\1\67\10\25\3\0"+
    "\11\25\21\0\2\25\3\0\17\25\1\70\5\25\3\0"+
    "\11\25\21\0\2\25\3\0\4\25\1\71\20\25\3\0"+
    "\11\25\21\0\2\25\3\0\21\25\1\72\3\25\3\0"+
    "\11\25\21\0\2\25\3\0\7\25\1\73\15\25\3\0"+
    "\11\25\21\0\2\25\3\0\14\25\1\74\10\25\3\0"+
    "\11\25\21\0\2\25\3\0\25\25\3\0\3\25\1\75"+
    "\5\25\67\0\1\76\2\45\2\0\63\45\57\0\1\77"+
    "\7\0\12\53\1\100\54\53\2\54\2\0\63\54\20\0"+
    "\2\101\3\0\6\101\22\0\2\101\30\0\2\25\3\0"+
    "\2\25\1\102\22\25\3\0\11\25\21\0\2\25\3\0"+
    "\20\25\1\103\4\25\3\0\11\25\21\0\2\25\3\0"+
    "\3\25\1\104\21\25\3\0\11\25\21\0\2\25\3\0"+
    "\15\25\1\105\7\25\3\0\11\25\21\0\2\25\3\0"+
    "\24\25\1\106\3\0\11\25\21\0\2\25\3\0\21\25"+
    "\1\107\3\25\3\0\11\25\21\0\2\25\3\0\15\25"+
    "\1\110\7\25\3\0\11\25\21\0\2\25\3\0\16\25"+
    "\1\111\6\25\3\0\11\25\21\0\2\25\3\0\17\25"+
    "\1\112\5\25\3\0\11\25\21\0\2\25\3\0\4\25"+
    "\1\113\20\25\3\0\11\25\21\0\2\25\3\0\21\25"+
    "\1\114\3\25\3\0\11\25\21\0\2\25\3\0\25\25"+
    "\3\0\5\25\1\115\3\25\65\0\1\116\2\0\12\53"+
    "\1\117\4\53\1\120\47\53\20\0\2\25\3\0\23\25"+
    "\1\121\1\25\3\0\11\25\21\0\2\25\3\0\4\25"+
    "\1\122\20\25\3\0\11\25\21\0\2\25\3\0\3\25"+
    "\1\123\4\25\1\124\5\25\1\125\6\25\3\0\11\25"+
    "\21\0\2\25\3\0\1\126\24\25\3\0\11\25\21\0"+
    "\2\25\3\0\6\25\1\127\16\25\3\0\11\25\21\0"+
    "\2\25\3\0\4\25\1\130\20\25\3\0\11\25\21\0"+
    "\2\25\3\0\10\25\1\131\14\25\3\0\11\25\21\0"+
    "\2\25\3\0\14\25\1\132\10\25\3\0\11\25\21\0"+
    "\2\25\3\0\10\25\1\133\14\25\3\0\11\25\21\0"+
    "\2\25\3\0\25\25\3\0\10\25\1\134\56\0\1\135"+
    "\11\0\12\53\1\117\4\53\1\0\47\53\20\0\2\25"+
    "\3\0\1\136\24\25\3\0\11\25\21\0\2\25\3\0"+
    "\4\25\1\137\20\25\3\0\11\25\21\0\2\25\3\0"+
    "\5\25\1\140\17\25\3\0\11\25\21\0\2\25\3\0"+
    "\17\25\1\141\5\25\3\0\11\25\21\0\2\25\3\0"+
    "\21\25\1\142\3\25\3\0\11\25\21\0\2\25\3\0"+
    "\17\25\1\143\5\25\3\0\11\25\21\0\2\25\3\0"+
    "\1\144\24\25\3\0\11\25\21\0\2\25\3\0\14\25"+
    "\1\145\10\25\3\0\11\25\21\0\2\25\3\0\12\25"+
    "\1\146\12\25\3\0\11\25\62\0\1\147\25\0\2\25"+
    "\3\0\17\25\1\150\5\25\3\0\11\25\21\0\2\25"+
    "\3\0\2\25\1\151\22\25\3\0\11\25\21\0\2\25"+
    "\3\0\15\25\1\152\7\25\3\0\11\25\21\0\2\25"+
    "\3\0\1\153\24\25\3\0\11\25\21\0\2\25\3\0"+
    "\21\25\1\154\3\25\3\0\11\25\21\0\2\25\3\0"+
    "\6\25\1\155\16\25\3\0\11\25\57\0\1\156\30\0"+
    "\2\25\3\0\23\25\1\157\1\25\3\0\11\25\21\0"+
    "\2\25\3\0\6\25\1\160\16\25\3\0\11\25\21\0"+
    "\2\25\3\0\13\25\1\161\11\25\3\0\11\25\64\0"+
    "\1\162\23\0\2\25\3\0\1\163\24\25\3\0\11\25"+
    "\21\0\2\25\3\0\17\25\1\164\5\25\3\0\11\25"+
    "\17\0\1\165\1\0\2\25\3\0\25\25\3\0\11\25"+
    "\21\0\2\25\3\0\17\25\1\166\5\25\3\0\11\25"+
    "\21\0\2\25\3\0\1\167\24\25\3\0\11\25\46\0"+
    "\1\170\41\0\2\25\3\0\13\25\1\171\11\25\3\0"+
    "\11\25\32\0\1\172\53\0\1\173\1\0\2\25\3\0"+
    "\25\25\3\0\11\25\30\0\1\174\104\0\1\175\67\0"+
    "\1\176\51\0\1\177\72\0\1\200\60\0\1\201\101\0"+
    "\1\202\72\0\1\203\61\0\1\204\62\0\1\205\73\0"+
    "\1\206\65\0\1\207\25\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5500];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\6\11\22\1\2\11\2\1\1\11"+
    "\1\0\1\11\2\0\1\11\1\1\1\0\1\1\1\0"+
    "\3\11\15\1\1\11\2\0\15\1\2\0\1\11\14\1"+
    "\1\0\11\1\1\0\6\1\1\0\3\1\1\11\2\1"+
    "\1\0\2\1\1\0\1\1\12\0\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
/**
*   Instancia de tabla de simbolos
*
*/
TablaSimbolos symtbl = new TablaSimbolos("ts.txt");




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return null;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline);
            }
          // fall through
          case 43: break;
          case 2:
            { /* se ignora */
            }
          // fall through
          case 44: break;
          case 3:
            { return new Symbol(sym.NOT, yyline, yycolumn, yytext());
            }
          // fall through
          case 45: break;
          case 4:
            { return new Symbol(sym.LPAREN, yyline, yycolumn, yytext());
            }
          // fall through
          case 46: break;
          case 5:
            { return new Symbol(sym.RPAREN, yyline, yycolumn, yytext());
            }
          // fall through
          case 47: break;
          case 6:
            { return new Symbol(sym.MULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 48: break;
          case 7:
            { return new Symbol(sym.MAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 49: break;
          case 8:
            { return new Symbol(sym.COMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 50: break;
          case 9:
            { return new Symbol(sym.MENOS, yyline, yycolumn, yytext());
            }
          // fall through
          case 51: break;
          case 10:
            { return new Symbol(sym.DIV, yyline, yycolumn, yytext());
            }
          // fall through
          case 52: break;
          case 11:
            { try {
        int valor = Integer.parseInt(yytext());
        if (valor < -32768 || valor > 32767) {
            throw new Error("ERROR: INT fuera de rango (" + yytext() + 
                ") en línea " + yyline);
        }
        symtbl.agregarSimbolo("_" + yytext(), "INT_CONST", yytext(), null);
        // System.out.println("Token INT_CONST encontrado, Lexema " + yytext());
        return new Symbol(sym.INT_CONST, yyline, yycolumn, valor);
    } catch (NumberFormatException e) {
        throw new Error("ERROR: INT inválido: " + yytext() + " en línea " + yyline);
    }
            }
          // fall through
          case 53: break;
          case 12:
            { return new Symbol(sym.LT, yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 13:
            { return new Symbol(sym.ASSIGN, yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 14:
            { return new Symbol(sym.GT, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 15:
            { if (yytext().length() > 255) {
      throw new Error("ERROR: ID demasiado largo (" + yytext().length() +
          " caracteres) en línea " + yyline);
  }
  symtbl.agregarSimbolo(yytext(), "ID", "-", null);
  return new Symbol(sym.ID, yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 16:
            { return new Symbol(sym.LBRACK, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 17:
            { return new Symbol(sym.RBRACK, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 18:
            { return new Symbol(sym.NEQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 19:
            { if (yytext().length() > 255) {
        throw new Error("ERROR: STRING demasiado largo (" + yytext().length() +
            " caracteres) en línea " + yyline);
    }
    symtbl.agregarSimbolo("_" + yytext(), "STRING_CONST", yytext(), yytext().length());
    // System.out.println("Token STRING_CONST encontrado, Lexema " + yytext());
    return new Symbol(sym.STRING_CONST, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 20:
            { return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 21:
            { double v = Double.parseDouble(yytext());
    if (Math.abs(v) > 1000000) {
        throw new Error("ERROR: FLOAT fuera de rango (" + yytext() + 
            ") en línea " + yyline);
    }
    symtbl.agregarSimbolo("_" + yytext(), "FLOAT_CONST", yytext(), null);
    // System.out.println("Token FLOAT_CONST encontrado, Lexema " + yytext());
    return new Symbol(sym.FLOAT_CONST, yyline, yycolumn, v);
            }
          // fall through
          case 63: break;
          case 22:
            { return new Symbol(sym.LE, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 23:
            { return new Symbol(sym.EQ, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 24:
            { return new Symbol(sym.GE, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 25:
            { return new Symbol(sym.IF, yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 26:
            { return new Symbol(sym.OR, yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 27:
            { int value = Integer.parseInt(yytext().substring(2), 16);
    if (value > 0xFFFF) {
        throw new Error("ERROR: HEX fuera de rango (" + yytext() + 
            ") en línea " + yyline);
    }
    symtbl.agregarSimbolo(yytext(), "HEX_CONST", String.valueOf(value), null);
    // System.out.println("Token HEX_CONST encontrado, Lexema " + yytext());
    return new Symbol(sym.HEX_CONST, yyline, yycolumn, value);
            }
          // fall through
          case 69: break;
          case 28:
            { return new Symbol(sym.TYPE_HEX, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 29:
            { return new Symbol(sym.TYPE_INT, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 30:
            { return new Symbol(sym.ELSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 31:
            { return new Symbol(sym.THEN, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 32:
            { return new Symbol(sym.SHOW, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 33:
            { return new Symbol(sym.ENDIF, yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 34:
            { return new Symbol(sym.TYPE_FLOAT, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 35:
            { return new Symbol(sym.UNTIL, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 36:
            { return new Symbol(sym.DECVAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 37:
            { return new Symbol(sym.REPEAT, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 38:
            { return new Symbol(sym.TYPE_STRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 39:
            { return new Symbol(sym.FUNC_IGUALES, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 40:
            { return new Symbol(sym.ENDDECVAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 41:
            { return new Symbol(sym.PROGRAM_SECTION, yyline, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 42:
            { return new Symbol(sym.END_PROGRAM_SECTION, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
