
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.analizadorlexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHOW = 16;
  public static final int FUNC_IGUALES = 36;
  public static final int MULT = 28;
  public static final int GE = 20;
  public static final int LPAREN = 33;
  public static final int REPEAT = 2;
  public static final int RPAREN = 34;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int LT = 21;
  public static final int ENDDECVAR = 9;
  public static final int OR = 24;
  public static final int DIV = 29;
  public static final int UNTIL = 3;
  public static final int FLOAT_CONST = 39;
  public static final int TYPE_INT = 12;
  public static final int HEX_CONST = 41;
  public static final int TYPE_HEX = 15;
  public static final int ASSIGN = 30;
  public static final int IF = 4;
  public static final int ID = 37;
  public static final int LE = 19;
  public static final int EOF = 0;
  public static final int INT_CONST = 38;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MENOS = 27;
  public static final int NEQ = 18;
  public static final int TYPE_FLOAT = 13;
  public static final int EQ = 17;
  public static final int LBRACK = 31;
  public static final int DECVAR = 8;
  public static final int END_PROGRAM_SECTION = 11;
  public static final int ENDIF = 7;
  public static final int ELSE = 6;
  public static final int TYPE_STRING = 14;
  public static final int RBRACK = 32;
  public static final int THEN = 5;
  public static final int PROGRAM_SECTION = 10;
  public static final int STRING_CONST = 40;
  public static final int GT = 22;
  public static final int MAS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "REPEAT",
  "UNTIL",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "DECVAR",
  "ENDDECVAR",
  "PROGRAM_SECTION",
  "END_PROGRAM_SECTION",
  "TYPE_INT",
  "TYPE_FLOAT",
  "TYPE_STRING",
  "TYPE_HEX",
  "SHOW",
  "EQ",
  "NEQ",
  "LE",
  "GE",
  "LT",
  "GT",
  "AND",
  "OR",
  "NOT",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "ASSIGN",
  "LBRACK",
  "RBRACK",
  "LPAREN",
  "RPAREN",
  "COMA",
  "FUNC_IGUALES",
  "ID",
  "INT_CONST",
  "FLOAT_CONST",
  "STRING_CONST",
  "HEX_CONST"
  };
}

